DROP TABLE IF EXISTS `TENNIS_COURT_DETAILS`;

CREATE TABLE `TENNIS_COURT_DETAILS` (`COURT_ID` INT(11) NOT NULL AUTO_INCREMENT, `COURT_NAME` VARCHAR(255) DEFAULT NULL,
`SLOT_AVAILABLE` INT(11) NOT NULL, `VERSION` INT(11) NOT NULL, PRIMARY KEY (`COURT_ID`));

CREATE TABLE `COURT_OCCUPANCY_DETAILS` (`ID` INT(11) NOT NULL AUTO_INCREMENT,`USER_ID` int(11) NOT NULL, `COURT_ID` INT,
`VERSION` INT(11) NOT NULL,FOREIGN KEY (COURT_ID) REFERENCES TENNIS_COURT_DETAILS(COURT_ID),PRIMARY KEY (`ID`));